CREATE TABLE ALARM ('Id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 						'Name' TEXT NOT NULL,
 						'Description' TEXT NOT NULL,
 						'Resolution' TEXT,
 						'StatusCode' TEXT);

CREATE TABLE ALARMEVENT ('Id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 							'AlarmId' INTEGER,
 							'Timestamp' TEXT,
 							'DeviceId' INTEGER,
 							'SensorData' TEXT);

CREATE TABLE ALARMEVENTRESOLUTION ('Id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 									'AlarmEventId' INTEGER,
 									'UserId' INTEGER,
 									'Timestamp' TEXT);

CREATE TABLE DEVICES ('Id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 						'Name' TEXT NOT NULL,
 						'Location' TEXT NOT NULL,
 						'SensorType' TEXT NOT NULL,
 						'MeasureUnit' TEXT NOT NULL);

CREATE TABLE USERS ('Id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
					  'Name' TEXT NOT NULL,
					  'Function' TEXT);
